ecommerceproject/cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name="add_cart"),
    path('',views.cart_detail,name="cart_detail"),
    path('remove/<int:product_id>/',views.cart_remove,name="cart_remove"),
    path('full_remove/<int:product_id>/',views.full_remove,name="full_remove"),
]

ecommerceproject/ecommerceapp/urls.py
from django.urls import path
from . import views
app_name ='ecommerceapp'
urlpatterns=[
    path('',views.allProdCat,name='allProdCat'),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.ProdCatDetail,name='ProdCatDetail'),


]

ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from ecommerceapp import views
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.home,name='home'),
    path('ecommerceapp/',include('ecommerceapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include("cart.urls")),



]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerceproject/search_app/urls.py
from django.urls import path
from . import views

app_name="search_app"

urlpatterns=[
    path('',views.searchResult,name='searchResult'),
]

ecommerceproject/cart/models.py
from django.db import models
from ecommerceapp.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price*self.quantity
    def __str__(self):
        return self.product

ecommerceproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecommerceapp.models import Product
from . models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save();
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
                    product=product,
                    quantity=1,
                    cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=(cart_item.product.price * cart_item.quantity)
            counter+=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,"cart.html",dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity>1:
        cart_item.quantity-=1
        cart_item.save()
    else:
        cart_item.delete()
    return  redirect('cart:cart_detail')
def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@1,300&display=swap" rel="stylesheet">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
<div>
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        Welcome to the cart store where you can buy awsome items
{% endblock %}
{% block title %}
    Cart - Shop Your Favorite !!!
{% endblock %}
{% block content %}
{% if not cart_items %}
    <div>
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">
                Your shopping cart is empty
            </h1>
            <br>
            <p class="text-center">
                please click<a href="{% url 'ecommerceapp:allProdCat' %}">Here</a>
            </p>
        </div>
    </div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart
        </h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">Your Items</th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src={{cart_item.product.image.url}} class="float-left rounded custom_image" style="height:50px;width:50px;"></a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    SKU: {{cart_item.product.id}}
                    <br>
                    Unit Price: {{cart_item.product.price}}
                    QTY: {{cart_item.quantity}} * $ {{cart_item.product.price}}
                </td>
                <td>$ {{cart_item.sub_total}}</td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fas fa-plus-circle custom_icon"></i></a>&nbsp;
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-minus custom_icon"></i></a>&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i> </a>
                </td>
                {% else %}
                <td>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus custom_icon"></i></a>&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i> </a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    please review your shopping cart items before proceeding with the order payment.
                </td>
            </tr>
            <tr>
            <td class="text-left">
                Your total is <strong> $ {{ total }}</strong>
            </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'ecommerceapp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">CONTINUE SHOPPING</a>
        </div>
    </div>
</div><br>
{% endif %}
{% endblock %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.desc |truncatewords:155 }}
    {% else %}
        Welcome to the cart store where you can buy awsome items
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{category.name}}-Shop Mart
    {% else %}
        see our collections -shop mart
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
        <div class="row my_row_class">
            <div class="mx-auto">
                <p><a href="{% url 'ecommerceapp:allProdCat' %}">New collections</a>{{category.name}} </p>
            </div>
        </div>
    {% endif %}
<div class="mx-auto">
    {% if category %}
        <img class="my_image my_image_padding col-12" src="{{category.image.url}}" alt="{{category.name}}" style="height:600px;width:1600px;" >

</div><br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.desc}}</p>
</div>
    {% else %}
<div>
    <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="">
</div>
<br>
<div>
    <h1 class="text-center my_title"> Our Product Collections</h1>
    <p class="text-justify">Online shopping is a form of electronic commerce which allows consumers to directly buy goods or services from a seller over the Internet using a web browser or a mobile app.Online stores usually enable shoppers to use "search" features to find specific models, brands or items.</p>
</div>
    {% endif %}
<div class="container">
    <div class="row max-auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width: 18rem;">
                <a href="{{product.get_url}}" ><img class="card-img-top my_image" src="{{product.image.url}}" style="height:250px; width:250px;" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>${{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
<div class="text-center">
        {% for pg in products.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} activate {% endif %}">{{pg}}</a>
        {% endfor %}
</div>
    </div>
</div>
{% endblock %}

ecommerceproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; Avodha Training All Rights Reserved</p>
</div>

ecommerceproject/templates/header.html
{% load static %}
<div>
    <center>
        <img src="{% static 'img/shop.png' %}" alt="this is site logo">
    </center>
</div>

ecommerceproject/templates/login.html
{% load static %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
form {border: 3px solid #f1f1f1;}

input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

button {
  background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

button:hover {
  opacity: 0.8;
}

.imgcontainer {
  text-align: center;
  margin: 24px 0 12px 0;
}

img.avatar {
  width: 40%;
  border-radius: 50%;
}

.container {
  padding: 16px;
}
.button-main{
}
.forgot{
    align:right;
}

</style>
</head>
<body>
<center>
<h2>Login</h2>

<form action="login" method="post">
    {% csrf_token %}

<div>
  <div class="card-body" style="width:18rem;">
    <label><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="username" required>

    <label><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" required>
      <label>
          <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px"> Remember me
        </label>

    <button class="button-main" type="submit">Login</button>
      <p class="forgot">Forgot password? click here  <label>
          <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px">
        </label></p>

  </div>
</div>
</form>
    </center>
</body>
</html>

ecommerceproject/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
          	    <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Shop
            </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'ecommerceapp:allProdCat' %}">All products</a>
                      {% for cat in links %}
                    <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
                    {% endfor %}
                </div>

                </li>
              {% if item_count > 0 %}
            <li class="nav-item">
                <a class="nav-link" href="cart:cart_details"><i class="fas fa-cart-arrow-down">{{item_count}}</i></a>
                 <a class="btn btn-outline-success mr-sm-2" href="/cart"><i class="fas fa-shopping-cart">{{item_count}}</i></a>
            </li>
               {% endif %}

    </ul>
     {% if user.is_authenticated %}
         <h6 class="mr-sm-2">welcome, {{user.username}}</h6>
         {% else %}
         <h6 class="mr-sm-2">Welcome to Shopping Mart </h6>
         {% endif %}

         {% if user.is_authenticated %}
         <a class="btn btn-outline-success mr-sm-2" href="{% url 'ecommerceapp:logout' %}"><i class="fas fa-sign-out-alt"></i></a>
         {% else %}
         <a class="btn btn-outline-success mr-sm-2" href="{% url 'ecommerceapp:login' %}"><i class="fas fa-sign-in-alt"></i></a>
         <a class="btn btn-outline-success mr-sm-2" href="{% url 'ecommerceapp:register' %}"><i class="fas fa-user"></i></a>
         {% endif %}
     <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult' %}" method="get">
         {% csrf_token %}
         <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
         <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
     </form>
      </div>
</nav>

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.desc|truncatewords:155}}
{% endblock %}
{% block title %}
    {{product.name}}-shop Mart
{% endblock %}
{% block content %}
<div>
    <div>
        <p><a href="{% url 'ecommerceapp:allProdCat' %}">Home</a> |<a href="{{product.category.get_url}}"></a>{{product.name}} </p>
    </div>
    <div class=>
        <br>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div>
                <img src="{{product.image.url}}" style="height:200px; width:200px;" alt="{{product.name}}">
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <h1 class="my_prod_title"><{{product.name}}></h1>
                <p>${{product.price}}</p>
                <p class="my_title">Product Description</p>
                <p class="text-justify my_prod_text">{{product.desc}}</p>
                {% if product.stock <= 0 %}
                    <p class="text-justify my_prod_text"><b>Out of stock </b></p>
                {% else %}
                    <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add To Cart</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

ecommerceproject/templates/register.html
{% load static %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
form {border: 3px solid #f1f1f1;}

input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

button {
  background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

button:hover {
  opacity: 0.8;
}

.imgcontainer {
  text-align: center;
  margin: 24px 0 12px 0;
}
.third{
     background: url("/static/img/signup.jpg") 50% 0 no-repeat fixed;
     color: white;
     height: 650px;
     padding: 100px 0 0 0;
}

.container {
  padding: 16px;
}

h5{
    color:red;
}
.card-body{
    text-align:left;
}


</style>
</head>
<body>
<div class="third">
<center>
{% for message in messages %}
<h5>{{message}}</h5>
{% endfor %}
<h2>Sign Up Below</h2>

<form action="register" method="post">
    {% csrf_token %}

<div>
  <div class="card-body" style="width:18rem;">
    <label><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="username" required>

    <label><b>Email</b></label>
    <input type="text" placeholder="Enter email" name="email" required>

    <label><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" required>

    <label><b>Repeat Password</b></label>
    <input type="password" placeholder="Enter Password" name="password2" required>
     <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>

     <div class="clearfix">
          <button type="submit" class="signupbtn">Sign Up</button><br>
          <button type="button" class="cancelbtn">Cancel</button>
     </div>

  </div>
</div>
</form>
    </center>
</div>
</body>

</html>

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.desc|truncatewords:155}}
{% endblock %}
{% block title %}
    {{product.name}}-shop Mart
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text"> You have searched for: {{query}}</p>
</div>
<div class="container">
    <div class="row max-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width:18rem">
                <a href="{{product.get_url}}" ><img class="card-img-top my_image" src="{{product.image.url}}" style="height:250px; width:250px;" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>${{product.price}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">0 results found.</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}